### ISSUE TITLE
Service with name "Mezzio\Navigation\LaminasView\Helper\PluginManager" could not be created

### ISSUE THREAD

**Issue by Miles8of9** [mimmi20/mezzio-navigation-laminasviewrenderer#31]
https://github.com/mimmi20/mezzio-navigation-laminasviewrenderer/blob/9b0ee10566d87f14f056d8de0579befebb4ea8ab/src/ConfigProvider.php#L61

The above row causes error:
Service with name "Mezzio\Navigation\LaminasView\Helper\PluginManager" could not be created. Reason: Laminas\ServiceManager\AbstractPluginManager::__construct now expects a Interop\Container\ContainerInterface instance representing the parent container; please update your code

The service extends AbstractPluginManager which requires an instance of ContainerInterface, which is not available when using InvokableFactory

I see there was a factory class and you removed it in a commit few days ago, but it won't work without it...

**Comment by mimmi20** [comment]
Could you post the code of your project where you are using this class?
