### ISSUE TITLE
Pages array causes Could not load Container "Mezzio\Navigation\Navigation"

### ISSUE THREAD

**Issue by Miles8of9** [mimmi20/mezzio-navigation-laminasviewrenderer#33]
Using this simple navigation array you get error 500 as subject.
Comment or remove the 'pages' array and the menu is rendered correctly.
Adding the 'pages' array seems to cause the error.
I'm actively investigating to solve the problem but the error is too generic!

<pre>
declare(strict_types=1);

return [
    'navigation' =>
    [
        'default' =>
        [
            [
                'label' => 'Home',
                'route' => 'home',
                'pages' => [
                    [
                        'label' => 'Page 1',
                        'route' => 'api.ping'
                    ],
                    [
                        'label' => 'Page 2',
                        'route' => 'api.ping'
                    ],
                    [
                        'label' => 'Page 3',
                        'route' => 'api.ping'
                    ],
                ]
            ],
            [
                'label' => 'Ping',
                'route' => 'api.ping'
            ]
        ],
    ],
];
</pre>

**Comment by mimmi20** [comment]
Please update the dependencies. This schould be solved by [this PR](https://github.com/mimmi20/mezzio-navigation/pull/33)
