### ISSUE TITLE
Menu view helper renders menus but not submenus

### ISSUE THREAD

**Issue by Miles8of9** [mimmi20/mezzio-navigation-laminasviewrenderer#34]
https://github.com/mimmi20/mezzio-navigation-laminasviewrenderer/blob/653247d586e58de499fc8a6c1b0dc9fbaedfe9de/src/View/Helper/Navigation/Menu.php#L312

As subject, i'm not fully understanding what this method does, but it looks like that Menu helper has no code to render submenus.

**Comment by mimmi20** [comment]
Could you explain, what makes a Submenu different from a Menu?

**Comment by Miles8of9** [comment]
Right now only top menus are rendered when using Menu view helper. All children pages are ignored.
Using navigation config below, the list is rendered with only 3 items: Home, Company, Ping.
Is this the chosen behavior?

This helper is useful indeed, but i would also add a bootstrap menu view helper to render navigation menus in Bootstrap format [https://getbootstrap.com/docs/4.5/components/navbar/](url) 

<pre>
declare(strict_types=1);

return [
    'navigation' =>
    [
        'default' =>
        [
            [
                'type'  => 'route',
                'label' => 'Home',
                'route' => 'home',
            ],
            [
                'type' => 'uri',
                'label' => 'Company',
                'uri' => '#',
                'pages' => [
                    [
                        'type'  => 'route',
                        'label' => 'Contacts',
                        'route' => 'contact'
                    ],
                    [
                        'type'  => 'route',
                        'label' => 'Privacy',
                        'route' => 'privacy'
                    ],
                ]                
            ],
            [
                'type'  => 'route',
                'label' => 'Ping',
                'route' => 'api.ping'
            ]
        ],
    ],
];
</pre>

**Comment by mimmi20** [comment]
Please check again
