### ISSUE TITLE
What does Psr\Log have to do with rendering navigation?

### ISSUE THREAD

**Issue by tyrsson** [mimmi20/mezzio-navigation-laminasviewrenderer#353]
# new Issue

| Q               | A          |
|-----------------|------------|
| project version | latest     |
| PHP version     | 8.3.0       |

## Steps required to reproduce the problem
Try to render the navigation via the helper without having your logger factories, whatever or wherever those happen to be....

## Expected Result
That the navigation container would be rendered by the helper
*

## Actual Result
Script dies with this:
Laminas \ ServiceManager \ Exception \ ServiceNotFoundException
Unable to resolve service "Mimmi20\Mezzio\Navigation\LaminasView\View\Helper\LoggerInterface" to a factory; are you certain you provided it during configuration?
*
It appears you left your error logging code in the helpers. That's my only guess.....

**Comment by mimmi20** [comment]
@tyrsson Could you prove the code, you used?

**Comment by tyrsson** [comment]
Yes, it'll be this evening before I'll have a chance to do so though.

**Comment by tyrsson** [comment]
I've overridden some of the GenericAuthorization classes to provide Assertion support, it's a must have for my use case.

This is from NavigationFactory:
```php
        assert($logger instanceof LoggerInterface);
        assert($htmlify instanceof HtmlifyInterface);
        assert($containerParser instanceof ContainerParserInterface);

        $helper = new Navigation($container, $logger, $htmlify, $containerParser);
```

Calling line:
```php
<?=$this->navigation('default')->menu();?>
```

Navigation block for testing:
```php
            'default' => [
                [
                    'label' => 'Login',
                    'route' => 'login',
                ],
                [
                    'label' => 'Logout',
                    'route' => 'logout',
                ],
                [
                    'label' => 'Account',
                    'route' => 'account.read',
                ]
            ],
```

Script dies with this:
Laminas \ ServiceManager \ Exception \ ServiceNotFoundException
Unable to resolve service "Mimmi20\Mezzio\Navigation\LaminasView\View\Helper\LoggerInterface"

Call stack at time of exception (I broke it up for readability)
Laminas\ServiceManager\ServiceManager->getFactory (c:\htdocs\axleus-test.local\vendor\laminas\laminas-servicemanager\src\ServiceManager.php:588)

Laminas\ServiceManager\ServiceManager->doCreate (c:\htdocs\axleus-test.local\vendor\laminas\laminas-servicemanager\src\ServiceManager.php:641)

Laminas\ServiceManager\ServiceManager->get (c:\htdocs\axleus-test.local\vendor\laminas\laminas-servicemanager\src\ServiceManager.php:264)

Mimmi20\Mezzio\Navigation\LaminasView\View\Helper\NavigationFactory->__invoke (c:\htdocs\axleus-test.local\vendor\mimmi20\mezzio-navigation-laminasviewrenderer\src\View\Helper\NavigationFactory.php:38)

Laminas\ServiceManager\ServiceManager->doCreate (c:\htdocs\axleus-test.local\vendor\laminas\laminas-servicemanager\src\ServiceManager.php:642)

Laminas\ServiceManager\ServiceManager->get (c:\htdocs\axleus-test.local\vendor\laminas\laminas-servicemanager\src\ServiceManager.php:264)

Laminas\ServiceManager\AbstractPluginManager->get (c:\htdocs\axleus-test.local\vendor\laminas\laminas-servicemanager\src\AbstractPluginManager.php:169)

Laminas\View\HelperPluginManager->get (c:\htdocs\axleus-test.local\vendor\laminas\laminas-view\src\HelperPluginManager.php:560)

Laminas\View\Renderer\PhpRenderer->plugin (c:\htdocs\axleus-test.local\vendor\laminas\laminas-view\src\Renderer\PhpRenderer.php:396)

Laminas\View\Renderer\PhpRenderer->__call (c:\htdocs\axleus-test.local\vendor\laminas\laminas-view\src\Renderer\PhpRenderer.php:415)

include (c:\htdocs\axleus-test.local\src\App\templates\layout\default.phtml:60)
Laminas\View\Renderer\PhpRenderer->render (c:\htdocs\axleus-test.local\vendor\laminas\laminas-view\src\Renderer\PhpRenderer.php:530)

Mezzio\LaminasView\LaminasViewRenderer->renderModel (c:\htdocs\axleus-test.local\vendor\mezzio\mezzio-laminasviewrenderer\src\LaminasViewRenderer.php:223)

Mezzio\LaminasView\LaminasViewRenderer->render (c:\htdocs\axleus-test.local\vendor\mezzio\mezzio-laminasviewrenderer\src\LaminasViewRenderer.php:126)

App\Handler\HomePageHandler->handle (c:\htdocs\axleus-test.local\src\App\src\Handler\HomePageHandler.php:83)
Laminas\Stratigility\Middleware\RequestHandlerMiddleware->process (c:\htdocs\axleus-test.local\vendor\laminas\laminas-stratigility\src\Middleware\RequestHandlerMiddleware.php:46)

Laminas\Stratigility\Next->handle (c:\htdocs\axleus-test.local\vendor\laminas\laminas-stratigility\src\Next.php:52)

Axleus\Core\Middleware\NavigationMiddleware->process (c:\htdocs\axleus-test.local\vendor\axleus\axleus-core\src\Middleware\NavigationMiddleware.php:62)

Mezzio\Middleware\LazyLoadingMiddleware->process (c:\htdocs\axleus-test.local\vendor\mezzio\mezzio\src\Middleware\LazyLoadingMiddleware.php:26)

Laminas\Stratigility\Next->handle (c:\htdocs\axleus-test.local\vendor\laminas\laminas-stratigility\src\Next.php:52)
Axleus\Core\Middleware\TemplateMiddleware->process (c:\htdocs\axleus-test.local\vendor\axleus\axleus-core\src\Middleware\TemplateMiddleware.php:53)

Mezzio\Middleware\LazyLoadingMiddleware->process (c:\htdocs\axleus-test.local\vendor\mezzio\mezzio\src\Middleware\LazyLoadingMiddleware.php:26)

Laminas\Stratigility\Next->handle (c:\htdocs\axleus-test.local\vendor\laminas\laminas-stratigility\src\Next.php:52)

Axleus\Message\Middleware\MessageMiddleware->process (c:\htdocs\axleus-test.local\vendor\axleus\axleus-message\src\Middleware\MessageMiddleware.php:37)

Mezzio\Middleware\LazyLoadingMiddleware->process (c:\htdocs\axleus-test.local\vendor\mezzio\mezzio\src\Middleware\LazyLoadingMiddleware.php:26)

Laminas\Stratigility\Next->handle (c:\htdocs\axleus-test.local\vendor\laminas\laminas-stratigility\src\Next.php:52)

Axleus\Authorization\Middleware\AuthorizationMiddleware->process (c:\htdocs\axleus-test.local\vendor\axleus\axleus-authorization\src\Middleware\AuthorizationMiddleware.php:92)

Mezzio\Middleware\LazyLoadingMiddleware->process (c:\htdocs\axleus-test.local\vendor\mezzio\mezzio\src\Middleware\LazyLoadingMiddleware.php:26)

Laminas\Stratigility\Next->handle (c:\htdocs\axleus-test.local\vendor\laminas\laminas-stratigility\src\Next.php:52)

Axleus\UserManager\Middleware\IdentityMiddleware->process (c:\htdocs\axleus-test.local\vendor\axleus\axleus-usermanager\src\Middleware\IdentityMiddleware.php:33)

Mezzio\Middleware\LazyLoadingMiddleware->process (c:\htdocs\axleus-test.local\vendor\mezzio\mezzio\src\Middleware\LazyLoadingMiddleware.php:26)

Laminas\Stratigility\Next->handle (c:\htdocs\axleus-test.local\vendor\laminas\laminas-stratigility\src\Next.php:52)

Axleus\Core\Middleware\EventManagerMiddleware->process (c:\htdocs\axleus-test.local\vendor\axleus\axleus-core\src\Middleware\EventManagerMiddleware.php:26)

Mezzio\Middleware\LazyLoadingMiddleware->process (c:\htdocs\axleus-test.local\vendor\mezzio\mezzio\src\Middleware\LazyLoadingMiddleware.php:26)

Laminas\Stratigility\Next->handle (c:\htdocs\axleus-test.local\vendor\laminas\laminas-stratigility\src\Next.php:52)

Mezzio\Session\SessionMiddleware->process (c:\htdocs\axleus-test.local\vendor\mezzio\mezzio-session\src\SessionMiddleware.php:27)

Prior to this is standard Mezzio Middleware

**Comment by mimmi20** [comment]
The Logger is now removed.

> I've overridden some of the GenericAuthorization classes to provide Assertion support, it's a must have for my use case.

Feel free to open a feature request to add the Assertions to my packages, if it is helpful.
