### ISSUE TITLE
Docs reference setAcl method instead of setAuthorization

### ISSUE THREAD

**Issue by tyrsson** [mimmi20/mezzio-navigation-laminasviewrenderer#374]
See docs and below

https://github.com/mimmi20/mezzio-navigation-laminasviewrenderer/blob/8c301418ca7910660abedb4297ed01d5e07f0c87/src/View/Helper/Navigation/AbstractHelper.php#L375

**Comment by mimmi20** [comment]
@tyrsson Could you review the PR and look for any other Issue?

**Comment by tyrsson** [comment]
Sure thing. Will take a look first thing this evening.
