### ISSUE TITLE
Role is typed as string

### ISSUE THREAD

**Issue by tyrsson** [mimmi20/mezzio-navigation-laminasviewrenderer#375]
I'm unsure how I am supposed to pass a the return of UserInterface::getRoles() to setRole() when getRoles returns an array. The docs for Mezzio\Navigation referenced a single helper to use for rendering. This one. So I am unsure how to proceed. Any feedback on how to proceed would be greatly appreciated

https://github.com/mimmi20/mezzio-navigation-laminasviewrenderer/blob/8c301418ca7910660abedb4297ed01d5e07f0c87/src/View/Helper/Navigation/AbstractHelper.php#L82

**Comment by tyrsson** [comment]
I found a temp solution. Since I was overriding the NavigationMiddleware already. This is how I solved it until you decide how you are going to patch it, or let me know what I'm doing wrong :)

I pulled an instance of the navigation helper and injected it into the navigation middleware via its factory. Then used the following code after the call to $this->navigationConfig->setRouter($this->router);

```php
        $this->navigation->setAuthorization($this->authorization);
        $this->navigation->setRole(
            $request->getAttribute(UserInterface::class)->getRoles()[0]
        );
```

**Comment by mimmi20** [comment]
The role you have to set here, is the role of the page, not of the user. This allows to limit the access to the page to users with a specific role.

**Comment by tyrsson** [comment]
It appears that role from AbstractHelper is being passed directly to build for the AcceptHelper here

https://github.com/mimmi20/mezzio-navigation-laminasviewrenderer/blob/8c301418ca7910660abedb4297ed01d5e07f0c87/src/View/Helper/Navigation/AbstractHelper.php#L325

And being passed to isAllowed / isGranted here:

https://github.com/mimmi20/navigation-helper-acceptpage/blob/1b76e26cd2e4ffcf4dfe7b68fbc8c71efc3d4400/src/AcceptHelper.php#L72

**Comment by tyrsson** [comment]
> The role you have to set here, is the role of the page, not of the user. This allows to limit the access to the page to users with a specific role.

Pages do not have roles, they do not support roles. Never have. They get a resource and a privilege. The role always has to come from the user. Yes, it determines if the page is shown to the user based on role, which is the role that is passed in. That role and the resource and privilege attached to the page is what determines if the page is accepted or not.

**Comment by mimmi20** [comment]
@tyrsson Could you review the PR?

**Comment by tyrsson** [comment]
Sure thing.
